version: "3.6"

services:
  peripheral-manager-bluetooth:
    build: .
    restart: on-failure
    network_mode: "host"
    environment:
      - NUVLAEDGE_UUID=${NUVLAEDGE_UUID}
      - NUVLA_ENDPOINT=${NUVLA_ENDPOINT:-nuvla.io}
      - NUVLA_ENDPOINT_INSECURE=${NUVLA_ENDPOINT_INSECURE:-False}
    labels:
      - nuvlaedge.component=True
      - nuvlaedge.deployment=production
